import '../local_keys.dart';

Map<String, String> ar = {
  LocalKeys.kRequiredField: "حقل مطلوب",
  LocalKeys.kPhoneLength: "طول رقم التليفون",
  LocalKeys.kPasswordLength: "طول كلمة السر",
  LocalKeys.kPasswordsNoMatch: "كلمة السر غير مطابقة",
  LocalKeys.kContinue: "متابعة",
  LocalKeys.kChooseLanguage: "اختر اللغة",
  LocalKeys.kForgetPassword: "نسيت كلمة المرور",
  LocalKeys.kPhone: "التليفون",
  LocalKeys.ksave: "حفظ",
  LocalKeys.kCopiedClipboard: "تم النسخ",
  LocalKeys.kLocation: "الموقع",
  LocalKeys.kMap: "الخريطة",
  LocalKeys.kReportproblem: "ابلغ عن مشكلة",
  LocalKeys.kAssignedOrders: "الطلبات المُعينة",
  LocalKeys.kLogin: "تسجيل الدخول",
  LocalKeys.kPassword: "كلمة المرور",
  LocalKeys.kCreateNewPassword: "أنشئ كلمة مرور جديدة",
  LocalKeys.kNewPassword: "كلمة مرور جديدة",
  LocalKeys.kReNewPassword: "تحديث كلمة المرور",
  LocalKeys.kViewMap: "اعرض الخريطة",
  LocalKeys.kActionForOrder: "حالة الطلب",
  LocalKeys.kDelivered: "تم التوصيل",
  LocalKeys.kNotDelivered: "لم يتم التوصيل",
  LocalKeys.kOrders: "الطلبات",
  LocalKeys.kResendOTPAgain: "إعادة إرسال رمز التحقق",
  LocalKeys.kSentVerificationCode: "تم إرسال كود التأكيد",
  LocalKeys.kMobileNumber: "رقم الجوال",
  LocalKeys.kFillOTP: "املئ حقل رمز التحقق",
  LocalKeys.kConfirm: "تأكيد",
  LocalKeys.kSetting: "الإعدادات",
  LocalKeys.kFullname: "الاسم بالكامل",
  LocalKeys.kPhoneNumber: "رقم التليفون",
  LocalKeys.kReset: "إعادة ضبط",
  LocalKeys.kRenewPassword: "تحديث كلمة المرور",
  LocalKeys.kResetPassword: "إعادة ضبط كلمة المرور",
  LocalKeys.kAssigned: "تم التعيين",
  LocalKeys.kProfileSetting: "إعدادات الملف الشخصي",
  LocalKeys.kLanguage: "اللغة",
  LocalKeys.kSignOut: "تسجيل الخروج",
  LocalKeys.kviewall: "مشاهدة الكل",
  LocalKeys.kNoInternetConnection: "لا يوجد اتصال بالشبكة",
  LocalKeys.kNotDeliveredActions: "خيارات عدم التوصيل",
  LocalKeys.kNoResponse: "لم يتم الرد",
  LocalKeys.kOutOfCoverage: "خارج التغطية",
  LocalKeys.kOther: "أخرى",
  LocalKeys.kDescription: "الوصف",
  LocalKeys.kNoOrderYet:"لا توجد طلبات بعد",
};
