import '../local_keys.dart';

Map<String, String> en = {
  LocalKeys.kRequiredField: "",
  LocalKeys.kPhoneLength: "",
  LocalKeys.kPasswordLength: "",
  LocalKeys.kPasswordsNoMatch: "",
  LocalKeys.kContinue: "Continue",
  LocalKeys.kChooseLanguage: "Choose Language",
  LocalKeys.kForgetPassword: "Forget Password",
  LocalKeys.kPhone: "Phone",
  LocalKeys.ksave: "save",
  LocalKeys.kCopiedClipboard: "Copied to Clipboard",
  LocalKeys.kLocation: "Location",
  LocalKeys.kMap: "Map",
  LocalKeys.kReportproblem: "Report a problem",
  LocalKeys.kAssignedOrders: "Assigned Orders",
  LocalKeys.kLogin: "Login",
  LocalKeys.kPassword: "Password",
  LocalKeys.kCreateNewPassword: "Create New Password",
  LocalKeys.kNewPassword: "New Password",
  LocalKeys.kReNewPassword: "Re-New Password",
  LocalKeys.kViewMap: "View Map",
  LocalKeys.kActionForOrder: "Action For Order",
  LocalKeys.kDelivered: "Delivered",
  LocalKeys.kNotDelivered: "Not Delivered",
  LocalKeys.kOrders: "Orders",
  LocalKeys.kResendOTPAgain: "Resend OTP Again?",
  LocalKeys.kSentVerificationCode: "We Sent Verification Code to Your",
  LocalKeys.kMobileNumber: "Mobile Number",
  LocalKeys.kFillOTP: "Fill OTP",
  LocalKeys.kConfirm: "Confirm",
  LocalKeys.kSetting: "Setting",
  LocalKeys.kFullname: "Full name",
  LocalKeys.kPhoneNumber: "Phone Number",
  LocalKeys.kReset: "Reset",
  LocalKeys.kRenewPassword: "Re-new Password",
  LocalKeys.kResetPassword: "Reset Password",
  LocalKeys.kAssigned: "Assigned",
  LocalKeys.kProfileSetting: "Profile Setting",
  LocalKeys.kLanguage: "Language",
  LocalKeys.kSignOut: "Sign Out",
  LocalKeys.kviewall: "view all",
  LocalKeys.kNoInternetConnection: "No Internet Connection",
  LocalKeys.kNotDeliveredActions: "Not Delivered Actions",
  LocalKeys.kNoResponse: "No Response",
  LocalKeys.kOutOfCoverage: "Out Of Coverage",
  LocalKeys.kOther: "Other",
  LocalKeys.kDescription: "Description",
  LocalKeys.kNoOrderYet: "No Order Yet",
};
